### ISSUE TITLE
Invalid config `-c` command option

### ISSUE THREAD

**Issue by filipditrich** [petrzjunior/barrelgun#2]
Running `shoot -c config.file.js` passes `{ c: true }` in `options`

```
.option('-c', '--config <path>') 
```
https://github.com/petrzjunior/barrelgun/blob/cc1f55d9019a75099defef15db6020539abd8048/src/main.ts#L15

should be:
```
.option('-c, --config <path>') 
```

**Comment by petrzjunior** [comment]
Fixed in https://github.com/petrzjunior/barrelgun/commit/4718cb5836bd3f81596c36d042be2de772ae9b9e, release 1.3.0. Thank you!
